<?php

namespace Bundles\LotoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CartSetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartSetRepository extends EntityRepository
{
}
