<?php

namespace Bundles\LotoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends EntityRepository
{
    public function getNewsBySlug($slug)
    {
        $qb = $this->createQueryBuilder('n');
        $qb->andWhere('n.slug = :slug')
                ->setParameter(':slug', $slug);
        return $qb->getQuery()->getResult();
    }
    
    public function getNews($count)
    {
        return $this->createQueryBuilder('n')
                ->select('n.title', 'n.content', 'n.slug')
                ->setMaxResults($count)
                ->getQuery()
                ->getResult()
                ;
    }
}
