Bundles\LotoBundle\Entity\Cart:
    type: entity
    table: carts
    repositoryClass: Bundles\LotoBundle\Repository\CartRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    oneToMany:
        rows:
            targetEntity: Row
            mappedBy: cart
    manyToOne:
        cartSet:
            targetEntity: CartSet
            inversedBy: carts
            joinColumn:
                name: cart_set_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
