Bundles\LotoBundle\Entity\Number:
    type: entity
    table: number
    repositoryClass: Bundles\LotoBundle\Repository\NumberRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        number:
            type: integer
        status:
            type: smallint
            nullable: true
    manyToOne:
        row:
            targetEntity: Row
            inversedBy: numbers
            joinColumn:
                name: row_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
