Bundles\LotoBundle\Entity\Player:
    type: entity
    table: player
    repositoryClass: Bundles\LotoBundle\Repository\PlayerRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        wins:
            type: integer
            nullable: true
        rating:
            type: integer
            nullable: true
        wallet:
            type: integer
            nullable: true
        avatar:
            type: string
            length: 255
            nullable: true
    manyToMany:
        friends:
            targetEntity: Player
            invercedBy: friendWithMe
            joinTable: 
                name: friends
                joinColumns:
                    player_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    friend_player_id:
                        referencedColumnName: id
        friendWithMe:
            targetEntity: Player
            mappedBy: friends
    oneToMany:
        roomMembers:
            targetEntity: RoomMember
            mappedBy: player
    oneToOne:
        user:
            targetEntity: Bundles\UserBundle\Entity\User
            invercedBy: player
            joinColumn:
                name: user_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
