Bundles\LotoBundle\Entity\RoomMember:
    type: entity
    table: room_members
    repositoryClass: Bundles\LotoBundle\Repository\RoomMemberRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToOne:
        player:
            targetEntity: Player
            inversedBy: roomMembers
            joinColumn:
                name: player_id
                referencedColumnName: id
        room:
            targetEntity: Room
            inversedBy: roomMembers
            joinColumn:
                name: room_id
                referencedColumnName: id
    oneToOne:
        cartSet:
            targetEntity: CartSet
            inversedBy: roomMember
            joinColumn:
                name: cart_set_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
