Bundles\LotoBundle\Entity\Room:
    type: entity
    table: rooms
    repositoryClass: Bundles\LotoBundle\Repository\RoomRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        limitUser:
            type: integer
        privateIs:
            type: boolean
            nullable: true
            column: private_is
        fastIs:
            type: boolean
            nullable: true
            column: fast_is
        crazyIs:
            type: boolean
            nullable: true
            column: crazy_is
        rate:
            type: integer
            nullable: true
        winningNumbers:
            type: string
            length: 4095
            column: winning_numbers
    oneToMany:
        roomMembers:
            targetEntity: RoomMember
            mappedBy: room
    lifecycleCallbacks: {  }
