Bundles\LotoBundle\Entity\Row:
    type: entity
    table: rows
    repositoryClass: Bundles\LotoBundle\Repository\RowRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToOne:
        cart:
            targetEntity: Cart
            inversedBy: rows
            joinColumn:
                name: cart_id
                referencedColumnName: id
    oneToMany:
        numbers:
            targetEntity: Number
            mappedBy: row
    lifecycleCallbacks: {  }
