Bundles\LotoBundle\Entity\Row:
    type: entity
    table: null
    repositoryClass: Bundles\LotoBundle\Repository\RowRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    lifecycleCallbacks: {  }
